### PR TITLE
Move locktimes and Sequence to primitives

### PR DESCRIPTION
**Pull request by storopoli**
The `absolute` and `relative` locktimes as well as the `Sequence` are all primitive bitcoin types.

Move the `Sequence`, and `locktime` stuff over to `primitives`.

There is nothing surprising here, the consensus encoding stuff stays in `bitcoin` and we re-export everything from `blockdata`.

### CODE REVIEW

**Comment by storopoli** [comment]
:rotating_light: API BREAKING CHANGE DETECTED

**Comment by storopoli** [comment]
:rotating_light: API BREAKING CHANGE DETECTED

**Comment by Kixunil** [comment]
Why is the label not orange?

**Comment by storopoli** [comment]
Because this is my fork and I didn't had that label before here. GitHub labels are not copied when you fork a repo. See that all the labels are grey here

**Comment by Kixunil** [comment]
Oh, LOL, why did I get GH notification from your repo? :D

**Comment by storopoli** [comment]
> Oh, LOL, why did I get GH notification from your repo? :D

I don't know you've commented here... 😂 I am just replying...

**Comment by Kixunil** [comment]
I mean I got notified about your own PR in your own repo without setting up watching.

**Pull request closed without merging**
